# Insert instructions entries here
# Each [[instructions]] entry needs a description and a midi
# You can also specify any of the following:
# [instructions.lights]
# - What, if any, hue light groups to set brightness for, and what brightness to set
#   (See config.toml -> hue_groups for a list of all groups - use the lowercase name)
# - For a given group "group", you can set the brightness using either the "brightness" key or the "bpercent" key as follows:
#   - group.brightness = x (0 <= x <= 255)
#   - group.bpercent = "x%" (0.0 <= x <= 100.0), or
#   - group.bpercent = x (0.0 <= x <= 100.0)
# [instructions.misc]
# - Currently, this only supports "media" as a key
# [instructions.camera]
# - This supports two keys:
#   - autotrack, which should be true or false
#   - preset, a numbered preset on the camera

[[instructions]]
description = "Eyeballs Off"
midi = 82
[instructions.lights]
stage.bpercent = "0%"

[[instructions]]
description = "Good Friday"
midi = 81
[instructions.lights]
booth.bpercent = "25%"
sanctuary.brightness = 186 # This is like 73%... Might just make it 75%
stage.bpercent = "25%"

[[instructions]]
description = "TBD"
midi = 80
[instructions.lights]
booth.brightness = 25
sanctuary.brightness = 25

[[instructions]]
description = "Bright Test"
midi = 79
[instructions.lights]
booth.bpercent = "100%"
sanctuary.bpercent = "100%"

[[instructions]]
description = "Comfy"
midi = 78
[instructions.lights]
booth.bpercent = "25%"
sanctuary.brightness = 186 # This is like 73%... Might just make it 75%
stage.brightness = 0

[[instructions]]
description = "Who knows"
midi = 77
[instructions.lights]
booth.bpercent = "50%"
sanctuary.bpercent = "100%"
stage.brightness = 76 # this is like 29%

[[instructions]]
description = "Message"
midi = 76
[instructions.lights]
booth.bpercent = "25%"
sanctuary.bpercent = "100%"
stage.bpercent = "25%"

[[instructions]]
description = "tbd"
midi = 75
[instructions.lights]
booth.bpercent = "0%"
sanctuary.bpercent = "50%"
stage.brightness = 76 # this is like 29%

[[instructions]]
description = "Worship"
midi = 74
[instructions.lights]
booth.bpercent = "25%"
foyer.brightness = 230 # like 90%
sanctuary.brightness = 200 # like 78%
stage.bpercent = "25%"

[[instructions]]
description = "tbd"
midi = 73
[instructions.lights]
booth.bpercent = "0%"
sanctuary.bpercent = "0%"

[[instructions]]
description = "Spotify Toggle"
midi= 61
[instructions.misc]
media = "toggle"

[[instructions]]
description = "Camera 1"
midi = 62
[instructions.camera]
#autotrack = true
preset = 1

[[instructions]]
description = "Camera 2"
midi = 63
[instructions.camera]
autotrack = false
preset = 2

[[instructions]]
description = "Camera 3"
midi = 64
[instructions.camera]
autotrack = false
preset = 3

[[instructions]]
description = "Camera 4"
midi = 65
[instructions.camera]
autotrack = false
preset = 4

[[instructions]]
description = "Camera 5"
midi = 66
[instructions.camera]
autotrack = false
preset = 5
